global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using webapi.Contexto;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.EntityFrameworkCore;
global using webapi.Datos;
global using webapi.Models;
global using Microsoft.AspNetCore.Mvc;
global using System;